# Generated by Django 2.0.2 on 2018-02-20 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='名称')),
                ('display_name', models.CharField(max_length=255, unique=True, verbose_name='显示名称')),
                ('author', models.CharField(max_length=255, verbose_name='作者')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='开启')),
            ],
            options={
                'verbose_name': '爬虫信息',
                'verbose_name_plural': '爬虫信息',
            },
        ),
        migrations.CreateModel(
            name='SpiderMeta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='键名')),
                ('value', models.TextField(blank=True, default='', verbose_name='键值')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spiders.Spider', verbose_name='爬虫信息')),
            ],
            options={
                'verbose_name': '爬虫元数据',
                'verbose_name_plural': '爬虫元数据',
            },
        ),
    ]
