# Generated by Django 2.0.2 on 2018-03-31 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, default='', max_length=255, verbose_name='附件名称')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='附件大小')),
                ('status', models.CharField(choices=[('packaging', '打包中'), ('packaged', '已打包'), ('delivering', '投递中'), ('completed', '完成'), ('failed', '失败')], default='failed', max_length=20, verbose_name='投递状态')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='投递时间')),
                ('spider', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spiders.Spider', verbose_name='爬虫信息')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='投递用户')),
            ],
            options={
                'verbose_name': '投递日志',
                'verbose_name_plural': '投递日志',
            },
        ),
    ]
