#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
ver=`cat server/server/config/version.py | head -n1 | sed "s/version_name = '\(.*\)'/\1/"`
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             --build-arg VERSION=$ver \
             -t $IMAGE_NAME .
